---
chromadb:
  host: localhost
  port: 8080
  collection: "default"
  collection_similarity: "cosine"

vectorstore:
  score: 0.6
  max_objects: 10
  query_mode: "default"

service_type: "ollama"

ollama:
  base_url: "http://localhost:11434"
  model: "nomic-embed-text:latest"

openai:
  base_url: "http://localhost:11434"
  model: "nomic-embed-text:latest"
  api_key: "your_api_key"

llm:
  temperature: 0.8
  top_k: 40
  top_p: 0.9
  seed: 12345678
  num_predict: 256
  num_ctx: 2048
  bypass_rag: True
  system_prompt: "You are an helpful assistant tasked to retrieve informations from a knowledge base. You must respond precisely and in no more than four senteces. If you cannot respond please tell that you do not know the answer. Use the following context to answer the question."
  user_prompt: "Question: {question}
                Context: {context}

                Answer: "
