---
apiVersion: v1
kind: Service
metadata:
  name: llm-frontend-service
  labels:
    app: llm-frontend
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: llm-frontend
  type: ClusterIP
