---
chromadb:
  host: chromahost
  port: 8080
  collection: "redhat"
  collection_similarity: "cosine"

vectorstore:
  score: 0.6
  max_objects: 10
  query_mode: "default"

service_type: "openai"

ollama:
  base_url: "http://localhost:11434"
  model: "granite3.2:2b"

openai:
  base_url: "https://openai-endpoint/v1"
  model: "tinyllama"
  api_key: "your_api_key"

llm:
  temperature: 0.8
  top_k: 40
  top_p: 0.9
  seed: 12345678
  num_predict: 256
  num_ctx: 2048
  bypass_rag: True
  system_prompt: "You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise. If the Context contains data, please cite that data in your answer. Your answers are polite and complete but always truthful. Try to be clear and concise, give examples if they are needed for clarification."
  user_prompt: "Question: {question}
                Context: {context}

                Answer: "
